[theme]
bg = "#232136"
tab_num = "#c4a7e7"
tab_divider = "#59546d"
bottombar_label = "#c4a7e7"
bottombar_text = "#e0def4"
bottombar_bg = "#2a273f"
scrollbar = "#393552"
hdg_1 = "#ea9a97"
hdg_2 = "#ea9a97"
hdg_3 = "#ea9a97"
amfora_link = "#f6c177"
foreign_link = "#9ccfd8"
link_number = "#817c9c"
regular_text = "#e0def4"
quote_text = "#3e8fb0"
preformatted_text = "#e0def4"
list_text = "#e0def4"
btn_bg = "#3e8fb0"
btn_text = "#e0def4"
dl_choice_modal_bg = "#2a273f"
dl_choice_modal_text = "#e0def4"
dl_modal_bg = "#2a273f"
dl_modal_text = "#e0def4"
info_modal_bg = "#2a273f"
info_modal_text = "#e0def4"
error_modal_bg = "#2a273f"
error_modal_text = "#eb6f92"
yesno_modal_bg = "#2a273f"
yesno_modal_text = "#e0def4"
tofu_modal_bg = "#2a273f"
tofu_modal_text = "#e0def4"
subscription_modal_bg = "#2a273f"
subscription_modal_text = "#e0def4"
input_modal_bg = "#2a273f"
input_modal_text = "#e0def4"
input_modal_field_bg = "#393552"
input_modal_field_text = "#e0def4"
bkmk_modal_bg = "#2a273f"
bkmk_modal_text = "#e0def4"
bkmk_modal_label = "#c4a7e7"
bkmk_modal_field_bg = "#393552"
bkmk_modal_field_text = "#e0def4"
