[theme]
bg = "#191724"
tab_num = "#c4a7e7"
tab_divider = "#555169"
bottombar_label = "#c4a7e7"
bottombar_text = "#e0def4"
bottombar_bg = "#1f1d2e"
scrollbar = "#26233a"
hdg_1 = "#ebbcba"
hdg_2 = "#ebbcba"
hdg_3 = "#ebbcba"
amfora_link = "#f6c177"
foreign_link = "#9ccfd8"
link_number = "#6e6a86"
regular_text = "#e0def4"
quote_text = "#31748f"
preformatted_text = "#e0def4"
list_text = "#e0def4"
btn_bg = "#31748f"
btn_text = "#e0def4"
dl_choice_modal_bg = "#1f1d2e"
dl_choice_modal_text = "#e0def4"
dl_modal_bg = "#1f1d2e"
dl_modal_text = "#e0def4"
info_modal_bg = "#1f1d2e"
info_modal_text = "#e0def4"
error_modal_bg = "#1f1d2e"
error_modal_text = "#eb6f92"
yesno_modal_bg = "#1f1d2e"
yesno_modal_text = "#e0def4"
tofu_modal_bg = "#1f1d2e"
tofu_modal_text = "#e0def4"
subscription_modal_bg = "#1f1d2e"
subscription_modal_text = "#e0def4"
input_modal_bg = "#1f1d2e"
input_modal_text = "#e0def4"
input_modal_field_bg = "#26233a"
input_modal_field_text = "#e0def4"
bkmk_modal_bg = "#1f1d2e"
bkmk_modal_text = "#e0def4"
bkmk_modal_label = "#c4a7e7"
bkmk_modal_field_bg = "#26233a"
bkmk_modal_field_text = "#e0def4"
