bg = "$base"
tab_num = "$iris"
tab_divider = "$highlightMed"
bottombar_label = "$iris"
bottombar_text = "$text"
bottombar_bg = "$surface"
scrollbar = "$highlightLow"

hdg_1 = "$iris"
hdg_2 = "$foam"
hdg_3 = "$rose"
amfora_link = "$gold"
foreign_link = "$subtle"
link_number = "$muted"
regular_text = "$text"
quote_text = "$text"
preformatted_text = "$text"
list_text = "$text"

btn_bg = "$pine"
btn_text = "$text"

dl_choice_modal_bg = "$surface"
dl_choice_modal_text = "$text"
dl_modal_bg = "$surface"
dl_modal_text = "$text"
info_modal_bg = "$surface"
info_modal_text = "$text"
error_modal_bg = "$surface"
error_modal_text = "$love"
yesno_modal_bg = "$surface"
yesno_modal_text = "$text"
tofu_modal_bg = "$surface"
tofu_modal_text = "$text"
subscription_modal_bg = "$surface"
subscription_modal_text = "$text"

input_modal_bg = "$surface"
input_modal_text = "$text"
input_modal_field_bg = "$overlay"
input_modal_field_text = "$text"

bkmk_modal_bg = "$surface"
bkmk_modal_text = "$text"
bkmk_modal_label = "$iris"
bkmk_modal_field_bg = "$overlay"
bkmk_modal_field_text = "$text"

